services:
  user_v1:
    image: ratfi/user_microservice_v1:latest
    build:
      context: ./user_microservice_v1
    ports:
      - "5001:5001"
    depends_on:
      - mongodb
      - rabbitmq

  user_v2:
    image: ratfi/user_microservice_v2:latest
    build:
      context: ./user_microservice_v2
    ports:
      - "5002:5002"
    depends_on:
      - mongodb
      - rabbitmq

  order_service:
    image: ratfi/order_microservice:latest
    build:
      context: ./order_microservice
    ports:
      - "5003:5003"
    depends_on:
      - mongodb
      - rabbitmq

  api_gateway:
    image: ratfi/api_gateway:latest
    build:
      context: ./api_gateway
    ports:
      - "80:8000"
    depends_on:
      - user_v1
      - user_v2
      - order_service

  event_handler:
    image: ratfi/event_handler:latest
    build:
      context: ./event_handler
    depends_on:
      - rabbitmq

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
