name: Docker Image CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-and-push:

    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --tag ${{ secrets.DOCKER_USERNAME }}/my-image-name:$(date +%s)

    - name: Push the Docker image
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/my-image-name:$(date +%s) ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/my-image-name:$(date +%s)
        docker push ${{ secrets.DOCKER_USERNAME }}/my-image-name:latest

  deploy:

    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/microservices_project
          docker-compose pull
          docker-compose up -d
